---
title: "Welcome"
author: "Talissa Floriani"
date: "26/10/2021"
output: html_document
---
# **Welcome - Tips**

Hello world! I'm a brazilian student, and since I started learning English, I decided to write this blog only in english (sometimes in portuguese), it will help me improve my writing skills and will also help you with your reading skills.   

But, this firsts post is going to be an exception, and I'm going to give you some tips to learn english without so much stress. Então vamos lá pessoal, as dicas vão ser em português, apenas nesse welcome post.  

- **1.LEIA MUITO!**
Sim, sem preguicinha, até porque tudo muda quando lemos algo que gostamos. Eu por exemplo, nunca fui muito fã de leitura, mas desde que vi a necessidade da leitura na minha área (pesquisa), me vi obrigada a ler. O que é engraçado é que quando estou lendo sobre o que gosto, eu nem percebo que o texto está em inglês, e isso se torna um hábito.   

- **2.MUDE AS REDES!**
Mude de português para inglês toda a sua vida cotidiana, por exemplo: Troque isso no Instagram, no Facebook... isso te obrigada a relacionar o que "settings" significa por exemplo. E settings significa configurações. Eu uso desde o meu sistema em si em inglês até as redes sociais, até meu spotify é versão inglês, e isso é muito bom.  

- **3.OUÇA MAIS!**
Escute mais músicas, podcasts, audiobooks... você encontra muitos arquivos de audiobooks free na internet, dê um google e voilá. Podcasts eu tenho os favoritos, eles são variados e vão desde podcasts para realmente ajudar no inglês até podcasts de comédia em inglês. Também dê um google e pesquise por suas preferências. Eu escuto pelo spotify, mas há vários no deezer também, apple music e por aí vai.   
Com relação as músicas, eu não posso dar muitas dicas, pois meus gostos são meio peculiares. Eles variam desde "System of a Down" até "Adele" hahaha sem julgamentos por favor, depende do humor.   

- **4.SEM LEGENDAS!**
Sem legendas em português, e não veja filmes dublados, sério, não faça isso! Muitas dublagens nem são boas e você acaba perdendo a qualidade do filme, e quando você coloca um filme em inglês com legenda em inglês ou sem legenda alguma, ahhh campeão, você se obriga a entender o que está acontecendo naquelas cenas e porque os atores estão se matando, ou não.  

- **5.BEBA E FALE!**
Quem nunca bebeu e soltou umas palavrinhas em inglês?! Sim, nós ficamos soltinhos no verbo quando bebemos, e se você tiver um parceiro de conversação, fica tudo mais fácil. Chama aquela melhor amiga para um vinho e solta o verbo, fala da vida, fofoca sobre o vizinho, faz os planos para o futuro, comenta sobre o cabelo, a roupa, a comida ... mas faz tudo isso em inglês.  

- **6.OUTRAS COISAS**
Tem muitaaa informação free na web. Youtube, Google a até mesmo no Linkedin você encontra pessoas postando informações sobre livros free que ajudaram no inglês, lives e videos free que ajudaram, até mesmo aulas de grátis online. Aplicativos como o Duolingo é uma excelente dica para quem quer aprender uma nova língua e isso vale até mesmo para Francês e Alemão.  
Há muitos sites que foram e continuam sendo úteis na minha vida com o inglês, aqui vão alguns:   

[Duolingo](https://pt.duolingo.com/)  
[Rachel's English](https://www.youtube.com/c/rachelsenglish)  
[TED](https://www.ted.com/)  

Xoxo:* 
